# Generated by Django 4.0.2 on 2022-02-27 22:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('88d971e1-ffb2-420e-a16a-a0cca584b38c'), editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('course_enrolled', models.CharField(blank=True, max_length=100)),
                ('study_type', models.CharField(blank=True, help_text='Bachelor Degree', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6d15f962-7e75-4292-beed-11a4f1175848'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('keyword', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4e7ee305-3baf-45c6-a633-a7abf83c939d'), editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('fluency', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('43b211df-4925-45dc-89a1-3c40fc231609'), editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=25)),
                ('postalCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('cea984f2-f88c-4f9d-a07d-46ab7981a883'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('published_on', models.CharField(blank=True, max_length=100)),
                ('date_published', models.DateField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c9a7e6be-b2e1-4004-84ea-b5efe78e8439'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('reference', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d2134f24-32b8-464d-88ed-b0d7c11707a2'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('814c4062-b49c-4113-8c9e-fa0c1ad025e7'), editable=False, primary_key=True, serialize=False)),
                ('network', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('76f9b587-90e8-411f-8128-8bb9dd857f3b'), editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company_summary', models.CharField(blank=True, max_length=255)),
                ('highlight', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('207c4c61-165c-4090-9212-ad999a314231'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.ImageField(upload_to='')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('website', models.URLField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.location')),
                ('social', models.ManyToManyField(blank=True, related_name='social_profiles', to='resume.SocialProfile')),
            ],
        ),
    ]
