# Generated by Django 4.0.2 on 2022-02-27 23:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5cb637a2-49b3-44d9-bc61-6dfff08e0302'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.UUIDField(default=uuid.UUID('defc473a-4534-4915-87a3-07bcda9de7db'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5960b55b-4ac1-4446-a51c-8326a1c60eca'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2bbc70b3-d07b-46cd-80ef-73de72c28904'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4eab668f-0d2a-4cfb-8389-a2485cba382b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7c91691-2143-4ac2-aece-e50e39ff243d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1ff55a9-e6de-482f-8d64-30dd1166e8b6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ee76ad9-4143-44a3-9002-0b07011b141e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e3bba3b-7aeb-4380-a8c7-9e8bc86a4c9d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('124ab5b2-dafe-4c12-a309-44b12b5deb62'), editable=False, primary_key=True, serialize=False),
        ),
    ]
