# Generated by Django 4.0.2 on 2022-02-28 00:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_basic_id_alter_education_id_alter_interest_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.AlterField(
            model_name='basic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('532d4c62-2933-4a1d-b62e-4da4e98340ab'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c6c700f7-b6e3-43b9-8778-21ee54a64324'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('584083be-71fe-428b-bebd-aa5bc85fc2a0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e0a5fb97-b9de-472f-a5c5-ee7ce6b5511d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2272cd95-c2ca-43b4-94b6-07afd1925ec0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ba6d36e1-3599-4ff0-9022-84bc2a41f030'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2e675a68-36b0-422e-acac-5b87d8817e85'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('84c3c395-6ce8-4ca2-95b8-6401279d245f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e1f8a1a6-088a-4e76-b4fa-02ced6ac51a4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7fc7e86e-805f-4c4f-b40b-593b8d3f98a3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
