# Generated by Django 4.0.2 on 2022-02-28 08:53

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_education_course_enrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc813fe3-b7c4-4f0c-a727-f402e0c48c5a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('108828ee-f622-488d-b7b6-bc26e3df095f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('81f9fc0f-8aa8-4647-ad6e-10a37ae60c94'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb16e689-df6e-4d32-b740-b12759b362de'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa818fc7-064b-4270-ab2f-a4be49a7bbb9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa9bba14-d82d-431f-85e4-317f99fdf1f6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.UUIDField(default=uuid.UUID('043f140b-650f-45ce-911e-63452bcb8c68'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48ed0190-d835-43fb-a441-41f6c0230b2c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d85b8987-d3c4-4abb-9493-efa98c7d039b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c6aa2354-561e-4df6-bc84-ca7585922cf0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='highlight',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6000add7-5b17-44a5-946f-a25fcfe773c1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
