# Generated by Django 4.0.2 on 2022-03-07 12:57

from django.db import migrations, models
import resumejson.storage_backends
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_education_id_alter_interest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.UUIDField(default=uuid.UUID('178bf790-cbb0-49a0-bbb3-3ab93894b1a0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c0ecf061-c318-4a00-9f3d-3a6ddeaec5ae'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fac4879c-ab8a-4c77-ac2f-beee3b3a1ef2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.UUID('89f1044b-a5f0-4b12-9603-52c7e5b89af2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95e93b98-0b2b-4e31-868a-c6e867276122'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=resumejson.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45d7440d-0ddb-4ffa-aeb6-4c3c75f4ac7b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80ef4db9-cce6-4155-b347-6ca0a7fce493'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e69db3d-c907-48f2-9193-f4f5812a0204'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('138471a1-cc5b-4d4c-927c-d98cabd6b2b5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b15ae894-fc67-423b-8ae4-b74f5c1cfa81'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5bc98823-952e-4f1c-8e6c-a0654bce62f6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
