# Generated by Django 4.0.2 on 2022-03-07 14:23

from django.db import migrations, models
import resumejson.storage_backends
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_alter_education_id_alter_interest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1aecd3dd-eaf1-4899-b172-b98995463d2b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d645fe53-91e6-41fd-8903-c79b69a46b38'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9d8f5691-504d-45d8-aeb8-00267f4574d6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7cfae45b-e063-4bed-99df-148d3ccf1830'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('62a098ba-14cd-431c-a951-1031625fc8fe'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=resumejson.storage_backends.PublicMediaStorage(), upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('33fd75fb-58ca-4c3b-ba74-b5b861c593d1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93c5ea13-b8be-414d-865f-bae9f0f339ab'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de95af06-5668-46aa-aeaf-9c8dff64ccab'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3872cb93-4be6-4b02-8f49-ddeead0f09ae'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f6baca3-b6b8-4fd3-9f28-8af367eb58cd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bc672f1a-f2ce-46d5-9db7-85c5dacf65fb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
