# Generated by Django 4.0.2 on 2022-03-07 15:33

from django.db import migrations, models
import resume.utils
import resumejson.storage_backends
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_alter_education_id_alter_interest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b048cda-f7b4-4e1e-aef1-b71860d66d98'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0dfd5e33-72c0-4593-8ef1-a2fe10b20646'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9a563fdc-8708-424c-9c18-923a8f9135ed'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c504a715-2ac0-47a7-9cd8-23e037cd7d56'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e100602b-552f-400b-91e8-f0caa27e3387'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=resumejson.storage_backends.PublicMediaStorage(), upload_to=resume.utils.generic_documents_directory),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('25cea151-d798-4ca7-9375-856730e2a585'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c18fd617-118d-4b94-9f38-35c414a5592d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b03fc17-8dad-4584-8bb9-57ca0065c9ee'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f8fc7f5-1400-4acd-bf5b-1fc7676c2dd8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4074df8-750e-4700-9a94-85f7c0b98429'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('da62782b-13d4-43de-bcf8-d07ecce8ed64'), editable=False, primary_key=True, serialize=False),
        ),
    ]
