# Generated by Django 4.0.2 on 2022-03-07 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_alter_education_id_alter_interest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95db44a2-7a78-4fe5-aac3-7b2249eb2072'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('15833608-0f78-4724-b53a-e8b6b71bf2ad'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0187b505-19bc-4b76-89d2-436859b8c21e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73848cec-80a6-4f11-8a60-c2c18d4d2710'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='id',
            field=models.UUIDField(default=uuid.UUID('87b1bba1-37d0-44f0-989e-19367c4d926e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('728f946a-1c5d-47a3-a2fe-7d6cbe1fcc46'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e6a58b1a-8a40-4995-8f1c-c5f51deac4ac'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ea2049b-6767-4e11-a998-2a4a139623b2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5f04671f-46ee-4771-8647-6bae2fbc9c47'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64b49708-92db-4c19-9287-bf9d561b4c3e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2a540cb6-800c-471a-89e6-df3fe3e73140'), editable=False, primary_key=True, serialize=False),
        ),
    ]
